//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotnetLocalWorkload {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizableStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizableStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotnetLocalWorkload.LocalizableStrings", typeof(LocalizableStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading {0} version {1} failed..
        /// </summary>
        internal static string DownloadVersionFailed {
            get {
                return ResourceManager.GetString("DownloadVersionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load NuGet source {0}.
        /// </summary>
        internal static string FailedToLoadNuGetSource {
            get {
                return ResourceManager.GetString("FailedToLoadNuGetSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load NuGet source {0}: the source is not valid. It will be skipped in further processing..
        /// </summary>
        internal static string FailedToLoadNuGetSourceSourceIsNotValid {
            get {
                return ResourceManager.GetString("FailedToLoadNuGetSourceSourceIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to validate package signing..
        /// </summary>
        internal static string FailedToValidatePackageSigning {
            get {
                return ResourceManager.GetString("FailedToValidatePackageSigning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not found in NuGet feeds {1}&quot;..
        /// </summary>
        internal static string IsNotFoundInNuGetFeeds {
            get {
                return ResourceManager.GetString("IsNotFoundInNuGetFeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip NuGet package signing validation. NuGet signing validation is not available on Linux or macOS https://aka.ms/workloadskippackagevalidation ..
        /// </summary>
        internal static string SkipNuGetpackageSigningValidationmacOSLinux {
            get {
                return ResourceManager.GetString("SkipNuGetpackageSigningValidationmacOSLinux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip NuGet package signing validation. The current .NET SDK is not signed by first party..
        /// </summary>
        internal static string SkipNuGetpackageSigningValidationSDKNotFirstParty {
            get {
                return ResourceManager.GetString("SkipNuGetpackageSigningValidationSDKNotFirstParty", resourceCulture);
            }
        }
    }
}
