// <auto-generated>
using System.Reflection;


namespace Microsoft.DotNet.Cli.NuGetPackageDownloader
{
    internal static partial class LocalizableStrings
    {
        private static global::System.Resources.ResourceManager s_resourceManager;
        internal static global::System.Resources.ResourceManager ResourceManager => s_resourceManager ?? (s_resourceManager = new global::System.Resources.ResourceManager(typeof(LocalizableStrings)));
        internal static global::System.Globalization.CultureInfo Culture { get; set; }
#if !NET20
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
#endif
        internal static string GetResourceString(string resourceKey, string defaultValue = null) =>  ResourceManager.GetString(resourceKey, Culture);
        /// <summary>Failed to load NuGet source {0}</summary>
        internal static string @FailedToLoadNuGetSource => GetResourceString("FailedToLoadNuGetSource");
        /// <summary>Failed to load NuGet source {0}: the source is not valid. It will be skipped in further processing.</summary>
        internal static string @FailedToLoadNuGetSourceSourceIsNotValid => GetResourceString("FailedToLoadNuGetSourceSourceIsNotValid");
        /// <summary>{0} is not found in NuGet feeds {1}".</summary>
        internal static string @IsNotFoundInNuGetFeeds => GetResourceString("IsNotFoundInNuGetFeeds");
        /// <summary>Downloading {0} version {1} failed.</summary>
        internal static string @DownloadVersionFailed => GetResourceString("DownloadVersionFailed");
        /// <summary>Skip NuGet package signing validation. The current .NET SDK is not signed by first party.</summary>
        internal static string @SkipNuGetpackageSigningValidationSDKNotFirstParty => GetResourceString("SkipNuGetpackageSigningValidationSDKNotFirstParty");
        /// <summary>Skip NuGet package signing validation. NuGet signing validation is not available on Linux or macOS https://aka.ms/workloadskippackagevalidation .</summary>
        internal static string @SkipNuGetpackageSigningValidationmacOSLinux => GetResourceString("SkipNuGetpackageSigningValidationmacOSLinux");
        /// <summary>Failed to validate package signing.</summary>
        internal static string @FailedToValidatePackageSigning => GetResourceString("FailedToValidatePackageSigning");

    }
}
